### ISSUE TITLE
Code style standardization

### ISSUE THREAD

**Issue by nemo1369** [boostorg/multiprecision#137]
Are there any code style standard the developer should keep close to?

I mean I'm going to bring a lot of changes in Boost.Multprecision, so we need to agree on some code style.

**Comment by jzmaddock** [comment]
I suppose I should really write a .clang.format file for the library!

I'm not going to get on too much of a bikeshed discussion over style, the most important thing is to keep the code well commented and easy to read and understand.  I personally prefer well spaced out code to dense/terse formatting as you'll notice from the existing code, but otherwise I hope I'm not overly fussy.

Oh and make any PR's so I can see what's changed - which is to say please don't mix up formatting changes with substantive changes if you can help it.

What changes were you planning?  The next big change I want to get back to is full constexpr support - I did a fair bit of work on this last year (https://github.com/boostorg/multiprecision/pull/84) but the effort stalled due to a lack of `std::is_constant_evaluated`.  Now that we are starting to see support for that I need to revisit that..... I do need to finish off hypergeometrics for Boost.Math first though ;)

**Comment by jzmaddock** [comment]
I've added a .clang-format file: it makes a lot of busy-body changes to existing code, but in the same spirit as what's there already (I hope!).

**Comment by nemo1369** [comment]
That is totally great! I'm gonna automatically reformat the code to be compliant to the .clang_format introduced and come back with some pull request. It makes some minor changes to spacing inside various operator definitions, but this makes no big change.

**Comment by nemo1369** [comment]
Coming to the full ```constexpr``` support, so I think, I would need to take this in sight, because my changes are all about underlying algorithms. I can make a monster-issue listing all the changes I want to bring, or I can create issue-by-issue along with pull requests with stuff I want to merge in. 

What would be the most convenient way to you?

**Comment by jzmaddock** [comment]
If you can avoid monster PR's that would be appreciated - it makes it really hard to figure out what's going on ;)

**Comment by nemo1369** [comment]
No, it is not about the monster PR, but about monster issue simply listing the upcoming changes.

**Comment by nemo1369** [comment]
Since #142 is merged, I think this is not relevant anymore.
