### ISSUE TITLE
Assertion failure in cpp_bin_float/transcendental.hpp

### ISSUE THREAD

**Issue by NAThompson** [boostorg/multiprecision#23]
The following code fails with an assertion:

```
#include <cmath>
#include <boost/multiprecision/cpp_bin_float.hpp>

template<class Real>
void reproduce_bug()
{
    using std::exp;
    Real z = boost::lexical_cast<Real>("3.12833694842469108932394792349501441046376844238532467151174529142282458046122837753372144306478e+304");
    std::cout << exp(-z) << std::endl;
}

int main()
{
    reproduce_bug<boost::multiprecision::cpp_bin_float_quad>();
}
```

This resuls in the following error message:

    a.out: ../multiprecision/include/boost/multiprecision/cpp_bin_float/transcendental.hpp:113: void boost::multiprecision::backends::eval_exp(boost::multiprecision::backends::cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE>&, const boost::multiprecision::backends::cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE>&) [with unsigned int Digits = 113u; boost::multiprecision::backends::digit_base_type DigitBase = (boost::multiprecision::backends::digit_base_type)2u; Allocator = void; Exponent = short int; Exponent MinE = -16382; Exponent MaxE = 16383]: Assertion `t.compare(default_ops::get_constant_ln2<cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE> >()) < 0' failed.

Using

    $g++ --version
    g++ (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

**Comment by ckormanyos** [comment]
> The following code fails an assertion:
That is interesting. We need to look at this.
What compiler? What general settings like optimization?

Sometimes automatic type inference is tricky with multiprecision.Multiprecision, in its default state, uses expression templates.These are challenging for compilers doing type inference.
I wonder what happens if the definition of f0 is made a bitmore specific like...
  auto f0 = [](Real x) -> Real { return log(x)*exp(-x); };

Best regards, Chris

 

    On Thursday, May 4, 2017 1:48 AM, Nick <notifications@github.com> wrote:
 

 The following code fails an assertion:template<class Real>
void reproduce_bug()
{
    auto f0 = [](Real x) { return log(x)*exp(-x); };
    Real z = boost::lexical_cast<Real>("3.12833694842469108932394792349501441046376844238532467151174529142282458046122837753372144306478e+304");
    std::cout << "z = " << z << std::endl;
    std::cout << f0(z) << std::endl;
}

int main()
{
    reproduce_bug<boost::multiprecision::cpp_bin_float_quad>();
}
This resuls in the following error message:a.out: ../multiprecision/include/boost/multiprecision/cpp_bin_float/transcendental.hpp:113: void boost::multiprecision::backends::eval_exp(boost::multiprecision::backends::cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE>&, const boost::multiprecision::backends::cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE>&) [with unsigned int Digits = 113u; boost::multiprecision::backends::digit_base_type DigitBase = (boost::multiprecision::backends::digit_base_type)2u; Allocator = void; Exponent = short int; Exponent MinE = -16382; Exponent MaxE = 16383]: Assertion `t.compare(default_ops::get_constant_ln2<cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE> >()) < 0' failed.

**Comment by ckormanyos** [comment]
>> The following code fails an assertion:
> That is interesting. We need to look at this.
Actually, the program crashes in a BOOST_ASSERTin eval_exp() in transcendental.hpp.

Maybe the exponent of z is so large that there is simplyan underflow problem with exp(-z)? It works when zhas been reduced Order(30).

This seems confusing.

Best regards, Chris 

    On Thursday, May 4, 2017 1:48 AM, Nick <notifications@github.com> wrote:
 

 The following code fails an assertion:template<class Real>
void reproduce_bug()
{
    auto f0 = [](Real x) { return log(x)*exp(-x); };
    Real z = boost::lexical_cast<Real>("3.12833694842469108932394792349501441046376844238532467151174529142282458046122837753372144306478e+304");
    std::cout << "z = " << z << std::endl;
    std::cout << f0(z) << std::endl;
}

int main()
{
    reproduce_bug<boost::multiprecision::cpp_bin_float_quad>();
}
This resuls in the following error message:a.out: ../multiprecision/include/boost/multiprecision/cpp_bin_float/transcendental.hpp:113: void boost::multiprecision::backends::eval_exp(boost::multiprecision::backends::cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE>&, const boost::multiprecision::backends::cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE>&) [with unsigned int Digits = 113u; boost::multiprecision::backends::digit_base_type DigitBase = (boost::multiprecision::backends::digit_base_type)2u; Allocator = void; Exponent = short int; Exponent MinE = -16382; Exponent MaxE = 16383]: Assertion `t.compare(default_ops::get_constant_ln2<cpp_bin_float<Digits, DigitBase, Allocator, Exponent, MinE, MaxE> >()) < 0' failed.

**Comment by NAThompson** [comment]
Well, it should underflow to zero, and in fact, that's what it does if you *increase* the argument. For instance, changing `z` to

    Real z = boost::lexical_cast<Real>("3.12e+384");

makes the assert failure go away.

**Comment by jzmaddock** [comment]
On 04/05/2017 23:38, Christopher Kormanyos wrote:
> >> The following code fails an assertion:
> > That is interesting. We need to look at this.
> Actually, the program crashes in a BOOST_ASSERTin eval_exp() in 
> transcendental.hpp.
>
> Maybe the exponent of z is so large that there is simplyan underflow 
> problem with exp(-z)? It works when zhas been reduced Order(30).

If the assert is being triggered then that's a bug (ie internal program 
logic failure).   Thanks for looking at this, let me know if you need a 
hand, John.


---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by jzmaddock** [comment]
I have a fix for this I'm testing now...

**Comment by jzmaddock** [comment]
Fixed in develop now.
