### ISSUE TITLE
Failures in Boost.Math misc test suite

### ISSUE THREAD

**Issue by mborland** [boostorg/multiprecision#375]
The quaternion tests are now failing using `cpp_dec_float` ([see here](https://github.com/boostorg/math/runs/3806626840?check_suite_focus=true#step:18:1251)). Looks to be an inexact comparison between a floating point type and an integer.

Bernoulli tests also now fail using `cpp_bin_float` as it registers as an unsupported configuration ([see here](https://github.com/boostorg/math/runs/3806626840?check_suite_focus=true#step:18:1296)).

**Comment by ckormanyos** [comment]
> quaternion tests are now failing using `cpp_dec_float` ... Looks to be an inexact comparison between a floating point...

Hi @mborland thenaks for finding this Matt!

Well, ... the fact that `cpp_dec_float` does not round has been present since the inception of `cpp_dec_float`.

Although this is not particularly _nice_, this behavior has not changed recently (although there is a completely separate, unmerged issue/branch related to this).

So I wonder what makes the difference in these tests now? Is it more exact knowledge or behavior of certain limbs when dealing with them within a `constexpr` context? Do we/I need to fundamentally change anything in `cpp_dec_float`? Or can we deal with that particular collection of test cases via tolerance increases?

Cc: @jzmaddock

**Comment by ckormanyos** [comment]
>>  what makes the difference in these tests now?

> the failing tests really should have exact integer results IMO

Yes. I will try to reproduce the behavior and go forward with debug.

**Comment by ckormanyos** [comment]
Hi @mborland I believe @jzmaddock handled this by disabling a handful of `cpp_dec_float` tests in Boost.Math's `misc`suite.

Can we close?

**Comment by NAThompson** [comment]
> Aaaahh, the Bernoulli failure isn't a failure - it's a test that is expected not to compile and the actual test does pass.

I got burned by this one as well. Is there a way just to not print anything on expected failures?

**Comment by jzmaddock** [comment]
Yes!

**Comment by jzmaddock** [comment]
>I got burned by this one as well. Is there a way just to not print anything on expected failures?

Not that I'm aware of.  The trick when searching for failures is to always search for "..failed" or "\.\.failed" if this is a regex (grep etc).

**Comment by NAThompson** [comment]
Ah I see. I always grepped for `error`.
