### ISSUE TITLE
is it possible to construct a new mpfr_float or mpc with a precision differing from default?

### ISSUE THREAD

**Issue by ofloveandhate** [boostorg/multiprecision#62]
i'd like to be able to construct real scalars at a given precision which differs from default.  the purpose is generating random numbers at any given precision without changing the default to do it.  am i ➿ ?

**Comment by jzmaddock** [comment]
I've pushed some fixes for this to develop, for mpfr_float you can now use a 2-arg constructor ( a value and a precision) and for mpc_complex a 3-arg constructor (real, imaginary and precision).  You can also use 2-arg copy-construction where the second arg is the precision (this one is only really useful for down-sampling the precision).  This was always intended, but got dropped due to overload resolution ambiguities and never reinstated.  I'm waiting for the CI tests to cycle, but it should all be working now.

**Comment by jzmaddock** [comment]
CI passing, closing.

**Comment by ofloveandhate** [comment]
thankyou!!!!!!
